services:
  nginx-main:
      image: nginx:stable
      container_name: nginx-service
      ports:
        - "80:80"
      networks:
        - api-network
      restart: unless-stopped
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/html:/usr/share/nginx/html:ro
  nginx-1:
      image: nginx:stable
      container_name: nginx-service-1
      depends_on:
        - nginx-main
      ports:
        - "80"
      networks:
        - api-network
      restart: unless-stopped
      volumes:
        - ./nginx/html/version1:/usr/share/nginx/html:ro
  nginx-2:
      image: nginx:stable
      container_name: nginx-service-2
      depends_on:
        - nginx-1
      ports:
        - "80"
      networks:
        - api-network
      restart: unless-stopped
      volumes:
        - ./nginx/html/version2:/usr/share/nginx/html:ro

networks:
  api-network:
    external: true